services:
  - type: web
    name: janus
    env: docker
    plan: free
    dockerContext: .
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_USER
        value: exchange_dev
      - key: DB_PASSWORD
        value: a1942340
      - key: DB_HOST
        value: 172.20.43.197
      - key: DB_NAME
        value: exchange
