services:
  crawler:
    build:
      context: ../
      dockerfile: ./docker/dockerfile.janus
    image: janus
    container_name: crawler
    volumes:
      - ../logs:/Janus/logs
      # - /data:/Janus/data
      - ../main/crontab.txt:/Janus/main/crontab.txt
    env_file:
      - ../.env.prod
    restart: always

  web:
    build:
      context: ../
      dockerfile: ./docker/dockerfile.javelin
    image: javelin
    container_name: web
    ports:
      - "5000:5000"
    volumes:
      - ../logs:/Javelin/logs
    env_file:
      - ../.env.prod
    restart: always

  predictor:
    build:
      context: ../
      dockerfile: ./docker/dockerfile.jervis
    image: jervis
    container_name: predictor
    volumes:
      - ../logs:/Jervis/logs
      # - ../data:/Janus/data
      - ../predictor/crontab.txt:/Jervis/predictor/crontab.txt
    env_file:
      - ../.env.prod
    restart: always